name: PR Title Check

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate PR title with regex
        id: validate_title
        run: |
          title="${{ github.event.pull_request.title }}"
          regex="^(feat|fix|docs)-\d+:(.*)$"
          if [[ ! "$title" =~ $regex ]]; then
            echo "title doesn't match"
            echo "::set-output name=title_valid::false"
          else
            echo "::set-output name=title_valid::true"
          fi

      - name: Close PR (if title doesn't match regex)
        if: steps.validate_title.outputs.title_valid == 'false'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.pull_request.number;
            const repo = context.payload.repository.name;
            const owner = context.payload.repository.owner.login;

            await github.issues.createComment({
              issue_number: issue_number,
              owner: owner,
              repo: repo,
              body: `
                Hey there! Thanks for your PR, but the title doesn't quite meet our quality checks. Please review our contribution guidelines. Your title should follow the format:

                \`\`\`
                fix-#124: Added responsiveness to the Home page screen
                \`\`\`

                Give it another shot with the proper format, and we'll be happy to reopen the PR for you.
                `
            });

            // Close the pull request
            await github.pulls.update({
              owner: owner,
              repo: repo,
              pull_number: issue_number,
              state: 'closed'
            });
            core.setFailed('PR title does not match the required format.');
